- hosts: siem
  tasks:
    - name: Install a list of packages
       apt:
        pkg:
        - curl
    - name: Install GPG "wazuh-agent"
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
    - name: Install repo
      shell: echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" > /etc/apt/sources.list.d/wazuh.list
    - name: Update repositories cache and install "wazuh-agent" package  
      apt:
        update_cache: yes
    - name: Install SIEM system
      shell: WAZUH_MANAGER="10.80.15.12" apt-get install wazuh-agent
    - name: Restart service "wazuh-agent", in all cases
      service:
        name: wazuh-agent
        state: started
        enabled: yes
    - name: Remove "wazuh-agent" apt update
      shell: sed -i "s/^deb/#deb/" /etc/apt/sources.list.d/wazuh.list
    - name: Update repositories cache and install "wazuh-agent" package  
      apt:
        update_cache: yes
