- hosts: azuracast.ghp.lc
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - htop
          - curl
          - ccze
          - net-tools
          - mc
          - wget
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: Create Directory
      command: mkdir -p /var/azuracast && cd /var/azuracast
    - name: Download script
      command: wget https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh
    - name: Change Permissions
      command: chmod a+x docker.sh && 
    - name: Change Permissions
      command: /var/azuracast/./docker.sh install
