- hosts: azuracast.ghp.lc
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - htop
          - curl
          - ccze
          - net-tools
          - mc
          - wget
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: Create Directory
      command: mkdir -p /var/azuracast
    - name: Download script
      command: wget https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/docker.sh -O /var/azuracast/docker.sh
    - name: Change Permissions
      command: chmod a+x /var/azuracast/docker.sh
    - name: Install Docker
      command: /var/azuracast/./docker.sh install-docker
    - name: Install Docker Compose
      command: /var/azuracast/./docker.sh install-docker-compose
#    - name: Install AzuraCast
#     command: yes '' | /var/azuracast/./docker.sh install
