- hosts: monitor-02.ghp.lc
  tasks:
    - name: (01) Install required system packages
      apt:
        pkg:
          - htop
          - curl
          - ccze
          - net-tools
          - mc
          - wget
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - php 
          - php-mysql 
          - php-common 
          - php-cli 
          - php-common 
          - php-json 
          - php-opcache 
          - php-readline 
          - php-mbstring 
          - php-gd 
          - php-dom 
          - php-zip 
          - php-curl
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: (02-1) Install Repo Zabbix 7
      command: mkdir /tmp/zabbix7
    - name: (02-2) Install Repo Zabbix 7
      command: wget -P /tmp/zabbix7 https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu22.04_all.deb
    - name: (02-3) Install Repo Zabbix 7
      command: dpkg -i /tmp/zabbix7/zabbix-release_7.0-2+ubuntu22.04_all.deb
    - name: (03) Install required system packages Zabbix
      apt:
        pkg:
          - zabbix-frontend-php 
          - zabbix-apache-conf 
          - zabbix-agent
          - zabbix-server-pgsql
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: Enable service Zabbix, in all cases
      service:
        name: zabbix-server
        enabled: yes
    - name: Change DB ip
      command: sed -i 's/^# DBHost=localhost/DBHost=10.80.6.123/g' /etc/zabbix/zabbix_server.conf
