- hosts: monitor-02.ghp.lc
  tasks:
    - name: (01) Install Repo Zabbix 7
      command: mkdir /tmp/zabbix7 && wget -P /tmp/zabbix7 https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu22.04_all.deb && dpkg -i /tmp/zabbix7/zabbix-release_7.0-2+ubuntu22.04_all.deb
    - name: (02) Install required system packages
      apt:
        pkg:
          - htop
          - curl
          - ccze
          - net-tools
          - mc
          - wget
          - zabbix-server-pgsql 
          - zabbix-frontend-php 
          - php8.1-pgsql 
          - zabbix-apache-conf 
          - zabbix-sql-scripts 
          - zabbix-agent
        state: latest
        force_apt_get: yes
        update_cache: true
