- hosts: monitor-02.ghp.lc
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - htop
          - 7zip
          - ccze
          - net-tools
          - mc
          - ifupdown
          - resolvconf
          - curl
          - git
    - name: (01) Mkdir
      command: mkdir /tmp/netplan
    - name: (02) Download netlan script
      command: git clone https://github.com/spd-it/Ansible-Playbook-Linux/blob/main/netplan.sh /tmp/netplan/netplan.sh
    - name: (03) Change permissions
      command: chmod +x /tmp/netplan/netplan.sh
    - name: (04) Remove Netplan
      command: /tmp/netplan/./netplan.sh
