- hosts: monitor-02.ghp.lc
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - htop
          - 7zip
          - ccze
          - net-tools
          - mc
          - ifupdown
          - resolvconf
          - curl
  tasks:
    - name: (01) Download netlan script
      command: wget -P /tmp https://github.com/spd-it/Ansible-Playbook-Linux/blob/main/netplan_remove.yaml
    - name: (02) Change permissions
      command: chmod +x /tmp/netplan_remove.yaml
    - name: (03) Remove Netplan
      command: /tmp/./netplan_remove.yaml
