---
- hosts: servers
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: (01) Install keyrings
      shell: install -m 0755 -d /etc/apt/keyrings
    - name: (02) Install Docker ca-certificates
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    - name: (03) Settings Docker Rules
      shell: chmod a+r /etc/apt/keyrings/docker.asc
    - name: (04) Install Docker repo
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Install required system packages
      apt:
        pkg:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: latest
        force_apt_get: yes
        update_cache: true
