- hosts: monitor-db-02.ghp.lc
  tasks:
    - name: (01) Install required system packages
      apt:
        pkg:
          - htop
          - curl
          - ccze
          - net-tools
          - mc
          - wget
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - php 
          - php-mysql 
          - php-common 
          - php-cli 
          - php-common 
          - php-json 
          - php-opcache 
          - php-readline 
          - php-mbstring 
          - php-gd 
          - php-dom 
          - php-zip 
          - php-curl
          - postgresql
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: (02-1) Install Repo Zabbix 6
      command: rm -rf /tmp/zabbix6
    - name: (02-2) Install Repo Zabbix 6
      command: mkdir /tmp/zabbix6
    - name: (02-3) Install Repo Zabbix 6
      command: wget -P /tmp/zabbix6 https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    - name: (02-4) Install Repo Zabbix 6
      command: dpkg -i /tmp/zabbix6/zabbix-release_6.4-1+ubuntu22.04_all.deb
    - name: (03) Install required system packages Zabbix
      apt:
        pkg:
          - zabbix-server-pgsql
          - php8.1-pgsql
          - zabbix-sql-scripts 
          - zabbix-agent
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: Change Listener Adress
      command: sed -i 's|listen_addresses = 'localhost'|listen_addresses = '*'|g' /etc/postgresql/14/main/postgresql.conf
    - name: (04) Access to DB Zabbix
      command: echo "host  all             all             10.80.6.122/32          password" >> /etc/postgresql/14/main/pg_hba.conf
      # sudo -u postgres createuser --pwprompt zabbix
      # sudo -u postgres createdb -O zabbix zabbix
      # zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
