- hosts: servers
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - htop
          - lsb_core
        state: latest
        force_apt_get: yes
        update_cache: true
