- name: Talk to all hosts just so we can learn about them
  hosts: servers
  tasks:
    - name: Classify hosts depending on their OS distribution
      ansible.builtin.group_by:
        key: os_{{ ansible_facts['distribution'] }}
