- hosts: monitor-02
  tasks:
    - name: (01) Install required system packages
      apt:
        pkg:
          - htop
          - curl
          - ccze
          - net-tools
          - mc
          - wget
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - php 
          - php-mysql 
          - php-common 
          - php-cli 
          - php-common 
          - php-json 
          - php-opcache 
          - php-readline 
          - php-mbstring 
          - php-gd 
          - php-dom 
          - php-zip 
          - php-curl
          - apache2
          - postgresql
          - snmp-mibs-downloader
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: (02-1) Install Repo Zabbix 6
      command: rm -rf /tmp/zabbix6
    - name: (02-2) Install Repo Zabbix 6
      command: mkdir /tmp/zabbix6
    - name: (02-3) Install Repo Zabbix 6
      command: wget -P /tmp/zabbix6 https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    - name: (02-4) Install Repo Zabbix 6
      command: dpkg -i /tmp/zabbix6/zabbix-release_6.4-1+ubuntu22.04_all.deb
    - name: (03) Install required system packages Zabbix
      apt:
        pkg:
          - zabbix-frontend-php 
          - zabbix-apache-conf 
          - zabbix-agent
          - zabbix-server-pgsql
          - php8.1-pgsql
          - zabbix-sql-scripts 
        state: latest
        force_apt_get: yes
        update_cache: true
    - name: Change DB ip
      command: sed -i 's/^# DBHost=localhost/DBHost=10.80.15.123/g' /etc/zabbix/zabbix_server.conf
    - name: Change Dir
      command: sed -i 's|DocumentRoot /var/www|DocumentRoot /usr/share/zabbix|g' /etc/apache2/sites-enabled/000-default.conf
    - name: Enable service Zabbix, in all cases
      service:
        name: apache2
        state: restarted
        enabled: yes
    - name: Enable service Zabbix, in all cases
      service:
        name: zabbix-server
        state: restarted
        enabled: yes
